import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";
import EventsContextProvider from "@/context/eventsContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <EventsContextProvider>
        <body className="bg-primary">
          <Navbar />
          <div className="flex gap-10 p-3 items-stretch">
            <Sidebar />
            {children}
          </div>
        </body>
      </EventsContextProvider>
    </html>
  );
}
