import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";
import EventsContextProvider from "@/context/eventsContext";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  console.log(process.env.NEXT_PUBLIC_API_URL);

  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap"
          rel="stylesheet"
        />
      </head>
      <EventsContextProvider>
        <body className="bg-primary">
          <Navbar />
          <div className="flex gap-10 p-3 items-stretch">
            <Sidebar />
            {children}
          </div>
        </body>
      </EventsContextProvider>
    </html>
  );
}
